---
- debug:
    msg: "IP {{ hostvars[groups['kube-master'][0]]['public_ipv4']  }}"

- name: Wait for galaxy API port
  wait_for:
          host: "{{ hostvars[groups['kube-master'][0]]['public_ipv4'] }}"
          port: 30700
          timeout: 600
          msg: "timeout connecting to galaxy server"

- name: Prepare exec pod
  template:
    src: "{{ role_path }}/files/exec-pod.yaml"
    dest: "/root/exec-pod.yaml"
    owner: root    

- name: Launch workflow execution pod
  command: kubectl create -f /root/exec-pod.yaml
  register: executor
  ignore_errors: true
  
