apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
data:
  username: "{{ lookup('env','S3_ID') | b64encode  }}"
  password: "{{  lookup('env','S3_KEY') | b64encode  }}"
  bucket: "{{  lookup('env','S3_BUCKET') | b64encode  }}"
